security:
  jwt:
    token:
      secret-key: ${TOKEN_SECRET:supersecret}

server:
  ssl:
    key-store-password: ${KEY_STORE_PASS:tfmamartinm}
    key-store: classpath:keystore.jks
  port: 8446

kafka:
  bootstrapAddress: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
  groupId: purchases-group
  topics:
    createShoppingCart: create-shopping-carts
    deleteShoppingCart: delete-shopping-carts
    completeShoppingCart: complete-shopping-carts
    createOrder: create-orders
    validateItems: validate-items
    updateItems: update-items
    updateOrder: update-orders
    restoreStock: restore-stock
    validateBalance: validate-balance
    changeState: change-orders-state

spring:
  datasource:
    url: jdbc:mysql://${RDS_HOSTNAME:localhost}:${RDS_PORT:3306}/${RDS_DATABASSE:purchases}
    username: ${RDS_USERNAME:root}
    password: ${RDS_PASSWORD:pass}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        types:
          print:
            banner: false
