security:
  jwt:
    token:
      secret-key: ${TOKEN_SECRET:supersecret}

server:
  ssl:
    key-store-password: tfmamartinm
    key-store: classpath:keystore.jks
  port: 8446

kafka:
  bootstrapAddress: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
  topics:
    set-item: set-items

spring:
  datasource:
    url: jdbc:mysql://${RDS_HOSTNAME:localhost}:${RDS_PORT:3306}/${RDS_DATABASSE:purchases}
    username: ${RDS_USERNAME:root}
    password: ${RDS_PASSWORD:pass}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
