apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.service" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "kafka.name" . }}
  annotations:
    dev.okteto.com/auto-ingress: 'false'
spec:
  ports:
    - port: {{ .Values.kafka.port }}
      name: {{ include "kafka.port" . }}
  clusterIP: None
  selector:
    app: {{ include "kafka.name" . }}
    release: {{ .Release.Name }}