apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "zookeeper.pdb" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "zookeeper.name" . }}
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ include "zookeeper.name" . }}
      release: {{ .Release.Name }}
  maxUnavailable: 1
