apiVersion: v1
kind: Service
metadata:
  name: {{ include "zookeeper.headless.service" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "zookeeper.name" . }}
    release: {{ .Release.Name }}
  annotations:
    dev.okteto.com/auto-ingress: 'false'
spec:
  ports:
  - port: {{ .Values.zookeeper.ports.server }}
    name: {{ include "zookeeper.server.port" . }}
  - port: {{ .Values.zookeeper.ports.le }}
    name: {{ include "zookeeper.le.port" . }}
  clusterIP: None
  selector:
    app: {{ include "zookeeper.name" . }}
    release: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "zookeeper.client.service" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "zookeeper.name" . }}
    release: {{ .Release.Name }}
  annotations:
    dev.okteto.com/auto-ingress: 'false'
spec:
  ports:
  - port: {{ .Values.zookeeper.ports.client }}
    name: {{ include "zookeeper.client.port" . }}
  selector:
    app: {{ include "zookeeper.name" . }}
    release: {{ .Release.Name }}
