---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: purchases-deploy
  namespace: tfm-dev-amartinm82
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: purchases
  replicas: 1
  template:
    metadata:
      labels:
        app: purchases
    spec:
      restartPolicy: Always
      securityContext:
        runAsUser: 1001
      containers:
      - name: purchases
        image: amartinm82/tfm-purchases:trunk
        imagePullPolicy: Always
        resources:
          requests:
            memory: "1Gi"
            cpu: "750m"
          limits:
            memory: "2Gi"
            cpu: "1250"
        env:
          - name: SPRING_DEVTOOLS_ADDPROPERTIES
            value: "false"
          - name: SPRING_DATASOURCE_URL
            value: jdbc:mysql://mysql-service:3306/purchases
          - name: SPRING_DATASOURCE_USERNAME
            value: root
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: purchases-secrets
                key: mysqlpass
          - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
            value: com.mysql.cj.jdbc.Driver
          - name: KAFKA_BOOTSTRAPADDRESS
            value: kafka-hs:9092
        ports:
        - containerPort: 8446

---
apiVersion: v1
kind: Service
metadata:
  name: purchases-service
  namespace: tfm-dev-amartinm82
  labels:
    app: purchases
  annotations:
    dev.okteto.com/auto-ingress: 'false'
spec:
  ports:
  - port: 8446
    targetPort: 8446
    protocol: TCP
    name: purchases-port
  selector:
    app: purchases
  type: LoadBalancer
